#!/usr/bin/env perl

my $count = 0;
my $width = 64;

my $head = qq(/* css file generated by img/iconcss.pl. Do not edit
this file by hand! Use the tool instead. */

.icon {
	background-image: url('/img/icon.svg');
	background-repeat: no-repeat;
}

);

sub css {
	($name) = @_;
	my $pos = $count*$width*-1;
	print qq(.icon-$name {
	background-position: ${pos}px 0px;
}

);
	$count++;
}

print $head;

while(<>) {
	/^%icon:(\w+):/ && css($1);
}
